project:
  type: website

website:
  title: "CFB Stats Scraper"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: scraper.qmd
        text: Scoring Scraper
      - href: generic_scraper.qmd
        text: Generic Scraper

format:
  html:
    theme: cosmo
    toc: true
